version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes: 
      - ./database/docker-data/mongo:/data/db
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
  webapp-service:
    image: node:8.11.4-slim
    restart: always
    container_name: graphql-api
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command:
      sh -c 'npm i && node server.js'
    ports:
      - "4000:4000"
    # environment:  
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - "mongo"