version: '3.1'
services:
  webapp-service:
    image: node:8.11.4-slim
    container_name: graphql-api
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command:
      sh -c 'npm i && node server.js'
    ports:
      - "4000:4000"
  mongo:
    image: mongo
    restart: always
    volumes: 
      - ./database/docker-data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example